### ISSUE TITLE
Why not use international dates?

### ISSUE THREAD

**Issue by getsnoopy** [wildlyinaccurate/wildlyinaccurate.github.io#22]
Hey mate. Seeing as you're from NZ, it's strange to see you using the illogical MDY ("Month DD, YYYY") date format on your blog. I recommend switching over to the international (RFC 2822) date format ("DD Month YYYY"):
https://github.com/wildlyinaccurate/wildlyinaccurate.github.io/blob/dfb68ef84fe6a035e2eed8887d4649f0f1c33042/_includes/post-meta.html#L2

**Comment by wildlyinaccurate** [comment]
Fair call! All dates are now DD M(M) YYYY.
